-- Contract category management (issue #414)
--
-- Creates a first-class `contract_categories` table so that categories are
-- flexible, admin-manageable objects rather than a hard-coded whitelist.
--
-- Key design decisions:
--   • Self-referencing parent_id enables unlimited category hierarchy depth.
--   • usage_count is NOT stored in the table; it is computed at query time via
--     a LEFT JOIN against contracts.category (text match on name).  This keeps
--     the schema simple and avoids trigger complexity across the contracts table.
--   • is_default marks seed categories that should never be fully removed.
--   • slug is a URL-safe identifier generated by the API layer on insert.

CREATE TABLE contract_categories (
    id          UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    name        VARCHAR(100) NOT NULL,
    slug        VARCHAR(100) NOT NULL,
    description TEXT,
    parent_id   UUID         REFERENCES contract_categories(id) ON DELETE SET NULL,
    is_default  BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_contract_categories_name UNIQUE (name),
    CONSTRAINT uq_contract_categories_slug UNIQUE (slug)
);

-- Fast name lookups (category validation, search)
CREATE INDEX idx_contract_categories_name  ON contract_categories(name);
-- Fast slug lookups (URL routing)
CREATE INDEX idx_contract_categories_slug  ON contract_categories(slug);
-- Fast subtree traversal
CREATE INDEX idx_contract_categories_parent ON contract_categories(parent_id)
    WHERE parent_id IS NOT NULL;

-- Reuse the update_updated_at_column() function already defined in
-- migration 001 so the updated_at column stays current automatically.
CREATE TRIGGER trg_contract_categories_updated_at
    BEFORE UPDATE ON contract_categories
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ── Seed default categories ──────────────────────────────────────────────────
-- These match the existing hard-coded whitelist in validation/requests.rs so
-- that existing contract data is immediately associated with a managed category.

INSERT INTO contract_categories (name, slug, description, is_default) VALUES
    ('DEX',     'dex',     'Decentralised exchange contracts',          TRUE),
    ('Lending', 'lending', 'Lending and borrowing protocol contracts',  TRUE),
    ('Bridge',  'bridge',  'Cross-chain bridge contracts',             TRUE),
    ('Oracle',  'oracle',  'Price-feed and data oracle contracts',     TRUE),
    ('Token',   'token',   'Fungible and non-fungible token contracts', TRUE),
    ('Other',   'other',   'Miscellaneous contracts',                  TRUE);
