pub fn contract_routes() -> Router<AppState> {
    Router::new()
        // Core contract operations
        .route(
            "/api/contracts",
            get(handlers::list_contracts).post(handlers::publish_contract),
        )
        .route("/api/contracts/tags", get(handlers::list_tags))
        .route("/api/contracts/export", post(handlers::export_contract_metadata))
        .route("/contracts/export", post(handlers::export_contract_metadata))
        .route("/api/contracts/export/:job_id", get(handlers::get_contract_export_status))
        .route("/contracts/export/:job_id", get(handlers::get_contract_export_status))
        .route(
            "/api/contracts/export/:job_id/download",
            get(handlers::download_contract_export),
        )
        .route(
            "/contracts/export/:job_id/download",
            get(handlers::download_contract_export),
        )
        .route(
            "/api/contracts/suggestions",
            get(handlers::get_contract_search_suggestions),
        )
        .route(
            "/api/contracts/trending",
            get(handlers::get_trending_contracts),
        )
        .route("/contracts/trending", get(handlers::get_trending_contracts))
        .route("/api/contracts/batch", post(handlers::get_contracts_batch))
        .route("/contracts/batch", post(handlers::get_contracts_batch))
        .route("/api/contracts/graph", get(handlers::get_contract_graph))
        .route("/api/contracts/:id", get(handlers::get_contract))
        .route(
            "/api/contracts/:id/metadata",
            patch(handlers::update_contract_metadata),
        )
        .route(
            "/api/contracts/:id/publisher",
            patch(handlers::change_contract_publisher),
        )
        .route(
            "/api/contracts/:id/status",
            patch(handlers::update_contract_status),
        )
        .route(
            "/api/contracts/:id/audit-log",
            get(handlers::get_contract_audit_log),
        )
        .route("/api/contracts/:id/abi", get(handlers::get_contract_abi))
        .route(
            "/api/contracts/:id/openapi.yaml",
            get(handlers::get_contract_openapi_yaml),
        )
        .route(
            "/api/contracts/:id/openapi.json",
            get(handlers::get_contract_openapi_json),
        )
        .route(
            "/api/contracts/:id/versions",
            get(handlers::get_contract_versions).post(handlers::create_contract_version),
        )
        .route(
            "/api/contracts/:id/versions/compare",
            get(handlers::compare_contract_versions),
        )
        .route(
            "/api/contracts/:id/versions/:version",
            get(handlers::get_specific_contract_version),
        )
        .route(
            "/api/contracts/:id/changelog",
            get(handlers::get_contract_changelog),
        )
        .route("/contracts/:id/changelog", get(handlers::get_contract_changelog))
        .route(
            "/api/contracts/breaking-changes",
            get(breaking_changes::get_breaking_changes),
        )
        .route(
            "/api/contracts/:id/patches",
            get(patch_handlers::list_contract_patches),
        )
        .route(
            "/api/contracts/:id/patches/:from_version/:to_version",
            get(patch_handlers::get_patch_between_versions),
        )
        .route(
            "/api/contracts/:id/patches/reconstruct",
            post(patch_handlers::reconstruct_contract_version),
        )
        .route(
            "/api/contracts/patches/bulk-apply",
            post(patch_handlers::bulk_apply_patches),
        )
        .route(
            "/api/contracts/:id/versions/:version/source",
            get(handlers::get_contract_source).post(handlers::upload_contract_source),
        )
        .route(
            "/api/contracts/:id/versions/:version/source/diff",
            get(handlers::get_contract_source_diff),
        )
        .route(
            "/api/contracts/:id/interactions",
            get(handlers::get_contract_interactions).post(handlers::post_contract_interaction),
        )
        .route(
            "/api/contracts/:id/interactions/batch",
            post(handlers::post_contract_interactions_batch),
        )
        .route(
            "/api/contracts/:id/deprecation-info",
            get(deprecation_handlers::get_deprecation_info),
        )
        .route(
            "/api/contracts/:id/deprecate",
            post(deprecation_handlers::deprecate_contract),
        )
        // AI-Powered Contract Code Assistant
        .route(
            "/api/contracts/:id/ai/chat",
            get(ai_handlers::ai_chat_handler).post(ai_handlers::ai_chat_handler),
        )
        .route(
            "/api/contracts/:id/ai/analyze",
            get(ai_handlers::analyze_contract_handler),
        )
        .route(
            "/api/contracts/:id/ai/vulnerabilities",
            get(ai_handlers::check_vulnerabilities_handler),
        )
        .route(
            "/api/contracts/:id/ai/explain",
            get(ai_handlers::explain_contract_handler),
        )
        .route(
            "/api/contracts/:id/ai/suggest",
            post(ai_handlers::suggest_code_handler),
        )
        .route(
            "/api/ai/chat",
            get(ai_handlers::ai_chat_handler).post(ai_handlers::ai_chat_handler),
        )
        .route(
            "/api/ai/sessions",
            get(ai_handlers::get_chat_sessions_handler),
        )
        .route(
            "/api/ai/sessions/:session_id",
            get(ai_handlers::get_chat_session_handler),
        )
        // Real-Time Contract State Monitor
        .route(
            "/api/contracts/:id/state/history",
            get(state_monitor_handlers::get_state_history_handler),
        )
        .route(
            "/api/contracts/:id/anomalies",
            get(state_monitor_handlers::get_contract_anomalies_handler),
        )
        .route(
            "/api/anomalies",
            get(state_monitor_handlers::get_anomalies_handler),
        )
        .route(
            "/api/anomalies/:anomaly_id/resolve",
            post(state_monitor_handlers::resolve_anomaly_handler),
        )
        // PostgreSQL Full-Text Search
        .route(
            "/api/search",
            get(search_postgres::fulltext_search_handler),
        )
        // Existing endpoints
        .route(
            "/api/contracts/:id/state/:key",
            get(handlers::get_contract_state)
                .put(handlers::update_contract_state)
                .post(handlers::update_contract_state),
        )
        .route(
            "/api/contracts/:id/analytics",
            get(analytics_handlers::get_contract_analytics),
        )
        .route(
            "/api/analytics/dashboard",
            get(analytics_handlers::get_analytics_dashboard),
        )
        .route(
            "/api/contracts/:id/dependencies",
            get(crate::dependency_handlers::get_contract_dependencies)
                // Issue #610: POST endpoint to declare/save dependencies
                .post(dependency_handlers::declare_contract_dependencies),
        )
        .route(
            "/api/contracts/:id/graph",
            get(handlers::get_contract_local_graph),
        )
        .route(
            "/api/contracts/:id/trust-score",
            get(handlers::get_trust_score),
        )
        .route(
            "/api/contracts/:id/dependents",
            get(handlers::get_contract_dependents),
        )
        .route(
            "/api/contracts/:id/impact",
            get(handlers::get_impact_analysis),
        )
        .route(
            "/api/contracts/:id/similar",
            get(similarity_handlers::get_similar_contracts),
        )
        .route(
            "/api/contracts/:id/recommendations",
            get(recommendation_handlers::get_contract_recommendations),
        )
        .route(
            "/api/contracts/:id/related",
            get(recommendation_handlers::get_contract_recommendations),
        )
        .route("/contracts/:id/recommendations", get(recommendation_handlers::get_contract_recommendations))
        .route("/contracts/:id/related", get(recommendation_handlers::get_contract_recommendations))
        .route("/contracts/:id/similar", get(similarity_handlers::get_similar_contracts))
        .route("/api/contracts/verify", post(handlers::verify_contract))
        .route(
            "/api/contracts/batch-verify",
            post(batch_verify_handlers::batch_verify_contracts),
        )
        .route(
            "/api/contracts/similarity/analyze",
            post(similarity_handlers::analyze_contract_similarity_batch),
        )
        .route(
            "/api/contracts/status/bulk",
            post(handlers::bulk_update_contract_status),
        )
        .route(
            "/api/contracts/:id/performance",
            get(performance_handlers::get_contract_performance_overview),
        )
        .route(
            "/api/contracts/:id/metrics",
            get(custom_metrics_handlers::get_contract_metrics)
                .post(custom_metrics_handlers::record_contract_metric),
        )
        .route(
            "/api/contracts/:id/resources",
            get(resource_handlers::get_contract_resources),
        )
        .route(
            "/api/contracts/:id/metrics/batch",
            post(custom_metrics_handlers::record_metrics_batch),
        )
        .route(
            "/api/contracts/:id/metrics/catalog",
            get(custom_metrics_handlers::get_metric_catalog),
        )
        .route(
            "/api/contracts/:id/compatibility",
            get(handlers::compatibility::get_contract_compatibility)
                .post(handlers::compatibility::add_contract_compatibility),
        )
        .route(
            "/api/contracts/:id/compatibility/export",
            get(handlers::compatibility::export_contract_compatibility),
        )
        .route(
            "/api/contracts/:id/interoperability",
            get(interoperability_handlers::get_contract_interoperability),
        )
        .route(
            "/api/contracts/:id/compatibility-matrix",
            get(compatibility_testing_handlers::get_compatibility_matrix),
        )
        .route(
            "/api/contracts/:id/compatibility-matrix/test",
            post(compatibility_testing_handlers::run_compatibility_test),
        )
        .route(
            "/api/contracts/:id/compatibility-matrix/history",
            get(compatibility_testing_handlers::get_compatibility_history),
        )
        .route(
            "/api/contracts/:id/compatibility-matrix/notifications",
            get(compatibility_testing_handlers::get_compatibility_notifications),
        )
        .route(
            "/api/contracts/:id/compatibility-matrix/notifications/read",
            post(compatibility_testing_handlers::mark_notifications_read),
        )
        .route(
            "/api/contracts/:id/deployments",
            get(handlers::get_contract_deployments),
        )
        .route(
            "/api/contracts/:id/deployments/status",
            get(handlers::get_deployment_status),
        )
        .route(
            "/api/contracts/:id/deployment-status",
            get(handlers::get_deployment_status),
        )
        .route("/api/deployments/green", post(handlers::deploy_green))
        .route(
            "/api/contracts/:id/deploy-green",
            post(handlers::deploy_green),
        )
        .route(
            "/contracts/simulate-deploy",
            post(simulation_handlers::simulate_deploy),
        )
        // Gas usage estimation
        .route(
            "/api/contracts/:id/methods/gas-estimate/batch",
            post(gas_estimation_handlers::batch_gas_estimate),
        )
        .route(
            "/api/contracts/:id/methods/:method/gas-estimate",
            get(gas_estimation_handlers::get_method_gas_estimate),
        )
        // Review system
        .route(
            "/api/contracts/:id/reviews",
            get(handlers::reviews::get_reviews).post(handlers::reviews::create_review),
        )
        .route(
            "/api/contracts/:id/reviews/:review_id/vote",
            post(handlers::reviews::vote_review),
        )
        .route(
            "/api/contracts/:id/reviews/:review_id/flag",
            post(handlers::reviews::flag_review),
        )
        .route(
            "/api/contracts/:id/reviews/:review_id/moderate",
            post(handlers::reviews::moderate_review),
        )
        .route(
            "/api/contracts/:id/rating-stats",
            get(handlers::reviews::get_rating_stats),
        )
        // Contract clone endpoints (#487)
        .route(
            "/api/contracts/:id/clone",
            post(clone_federation_handlers::clone_contract),
        )
        .route(
            "/api/contracts/:id/clones",
            get(clone_federation_handlers::get_contract_clones),
        )
        .merge(favorite_routes())
}