use anyhow::{Context, Result};
use colored::Colorize;
use std::fs;
use std::path::Path;

pub fn generate(
    contract_path: &str,
    lang: &str,
    output: Option<&str>,
    docs_output: Option<&str>,
) -> Result<()> {
    println!("\n{}", "Generating contract client code...".bold().cyan());

    let abi_json = load_abi_json(contract_path)?;
    let contract_name = Path::new(contract_path)
        .file_stem()
        .and_then(|stem| stem.to_str())
        .unwrap_or("contract");
    let abi = contract_abi::parse_json_spec(&abi_json, contract_name)
        .map_err(|err| anyhow::anyhow!("Failed to parse ABI: {}", err))?;

    let generated = match lang.to_lowercase().as_str() {
        "ts" | "typescript" => generate_typescript(&abi),
        "rust" | "rs" => generate_rust(&abi),
        "json" => serde_json::to_string_pretty(&abi)?,
        "md" | "markdown" => generate_markdown(&abi),
        _ => anyhow::bail!("Unsupported language '{}'", lang),
    };

    if let Some(output_path) = output {
        fs::write(output_path, generated)
            .with_context(|| format!("Failed to write generated output: {}", output_path))?;
        println!(
            "{} Generated {} output at {}",
            "✓".green(),
            lang,
            output_path
        );
    } else {
        println!("{}", generated);
    }

    if let Some(docs_path) = docs_output {
        let markdown = generate_markdown(&abi);
        fs::write(docs_path, markdown)
            .with_context(|| format!("Failed to write documentation: {}", docs_path))?;
        println!("{} Documentation written to {}", "✓".green(), docs_path);
    }

    Ok(())
}

fn load_abi_json(contract_path: &str) -> Result<String> {
    if contract_path.to_lowercase().ends_with(".wasm") {
        let output = std::process::Command::new("soroban")
            .args(["contract", "bindings", "json", "--wasm", contract_path])
            .output()
            .map_err(|err| anyhow::anyhow!("Failed to run soroban bindings: {}", err))?;
        if !output.status.success() {
            anyhow::bail!(
                "soroban bindings failed: {}",
                String::from_utf8_lossy(&output.stderr)
            );
        }
        Ok(String::from_utf8(output.stdout)?)
    } else {
        fs::read_to_string(contract_path)
            .with_context(|| format!("Failed to read ABI file: {}", contract_path))
    }
}

fn generate_typescript(abi: &contract_abi::ContractABI) -> String {
    let mut out = String::new();
    out.push_str("// Generated by soroban-registry generate\n\n");
    out.push_str(&format!("export interface I{}Client {{\n", abi.name));
    for function in abi.public_functions() {
        let params = function
            .params
            .iter()
            .map(|param| format!("{}: {}", param.name, ts_type(&param.param_type)))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!(
            "  {}({}): Promise<{}>;\n",
            function.name,
            params,
            ts_type(&function.return_type)
        ));
    }
    out.push_str("}\n\n");
    out.push_str(&format!(
        "export class {}Client implements I{}Client {{\n",
        abi.name, abi.name
    ));
    out.push_str("  constructor(private readonly contractId: string) {}\n\n");
    for function in abi.public_functions() {
        let params = function
            .params
            .iter()
            .map(|param| format!("{}: {}", param.name, ts_type(&param.param_type)))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!(
            "  async {}({}): Promise<{}> {{\n",
            function.name,
            params,
            ts_type(&function.return_type)
        ));
        out.push_str("    throw new Error('Generated client stub: wire RPC invocation here');\n");
        out.push_str("  }\n\n");
    }
    out.push_str("}\n");
    out
}

fn generate_rust(abi: &contract_abi::ContractABI) -> String {
    let mut out = String::new();
    out.push_str("// Generated by soroban-registry generate\n\n");
    out.push_str(&format!("pub struct {}Client {{\n", abi.name));
    out.push_str("    pub contract_id: String,\n");
    out.push_str("}\n\n");
    out.push_str(&format!("impl {}Client {{\n", abi.name));
    out.push_str("    pub fn new(contract_id: impl Into<String>) -> Self {\n");
    out.push_str("        Self { contract_id: contract_id.into() }\n");
    out.push_str("    }\n\n");
    for function in abi.public_functions() {
        let params = function
            .params
            .iter()
            .map(|param| format!("{}: {}", param.name, rust_type(&param.param_type)))
            .collect::<Vec<_>>()
            .join(", ");
        let rendered_params = if params.is_empty() {
            "&self".to_string()
        } else {
            format!("&self, {}", params)
        };
        out.push_str(&format!(
            "    pub fn {}({}) -> anyhow::Result<{}> {{\n",
            function.name,
            rendered_params,
            rust_type(&function.return_type)
        ));
        out.push_str(
            "        anyhow::bail!(\"Generated client stub: implement Soroban RPC call\")\n",
        );
        out.push_str("    }\n\n");
    }
    out.push_str("}\n");
    out
}

fn generate_markdown(abi: &contract_abi::ContractABI) -> String {
    let mut out = format!("# {}\n\n", abi.name);
    out.push_str("## Functions\n\n");
    for function in abi.public_functions() {
        out.push_str(&format!("### `{}`\n\n", function.name));
        if let Some(doc) = &function.doc {
            out.push_str(&format!("{}\n\n", doc));
        }
        if function.params.is_empty() {
            out.push_str("- Parameters: none\n");
        } else {
            out.push_str("- Parameters:\n");
            for param in &function.params {
                out.push_str(&format!(
                    "  - `{}`: `{}`\n",
                    param.name,
                    param.param_type.display_name()
                ));
            }
        }
        out.push_str(&format!(
            "- Returns: `{}`\n\n",
            function.return_type.display_name()
        ));
    }
    out
}

fn ts_type(kind: &contract_abi::SorobanType) -> String {
    match kind {
        contract_abi::SorobanType::Bool => "boolean".to_string(),
        contract_abi::SorobanType::I32
        | contract_abi::SorobanType::I64
        | contract_abi::SorobanType::I128
        | contract_abi::SorobanType::I256
        | contract_abi::SorobanType::U32
        | contract_abi::SorobanType::U64
        | contract_abi::SorobanType::U128
        | contract_abi::SorobanType::U256 => "number".to_string(),
        contract_abi::SorobanType::String | contract_abi::SorobanType::Symbol => {
            "string".to_string()
        }
        contract_abi::SorobanType::Void => "void".to_string(),
        contract_abi::SorobanType::Vec { element_type } => {
            format!("Array<{}>", ts_type(element_type))
        }
        contract_abi::SorobanType::Option { value_type } => {
            format!("{} | null", ts_type(value_type))
        }
        contract_abi::SorobanType::Map { .. } => "Record<string, unknown>".to_string(),
        contract_abi::SorobanType::Tuple { .. } => "unknown[]".to_string(),
        contract_abi::SorobanType::Struct { name, .. }
        | contract_abi::SorobanType::Enum { name, .. }
        | contract_abi::SorobanType::Custom { name } => name.clone(),
        _ => "unknown".to_string(),
    }
}

fn rust_type(kind: &contract_abi::SorobanType) -> String {
    match kind {
        contract_abi::SorobanType::Bool => "bool".to_string(),
        contract_abi::SorobanType::I32 => "i32".to_string(),
        contract_abi::SorobanType::I64 => "i64".to_string(),
        contract_abi::SorobanType::I128 => "i128".to_string(),
        contract_abi::SorobanType::U32 => "u32".to_string(),
        contract_abi::SorobanType::U64 => "u64".to_string(),
        contract_abi::SorobanType::U128 => "u128".to_string(),
        contract_abi::SorobanType::String | contract_abi::SorobanType::Symbol => {
            "String".to_string()
        }
        contract_abi::SorobanType::Void => "()".to_string(),
        contract_abi::SorobanType::Vec { element_type } => {
            format!("Vec<{}>", rust_type(element_type))
        }
        contract_abi::SorobanType::Option { value_type } => {
            format!("Option<{}>", rust_type(value_type))
        }
        contract_abi::SorobanType::Map { .. } => {
            "std::collections::BTreeMap<String, String>".to_string()
        }
        contract_abi::SorobanType::Struct { name, .. }
        | contract_abi::SorobanType::Enum { name, .. }
        | contract_abi::SorobanType::Custom { name } => name.clone(),
        _ => "String".to_string(),
    }
}
